### ISSUE TITLE
multi image detection / multiple occurences

### ISSUE THREAD

**Issue by x0rzkov** [yzhangcs/SoTu#6]
Hi,

Hope you are all well !

I was wondering if SoTu is able to make these 2 points:

# Detection of multiple occurrences of the same picture
For example, based on [find-object](https://github.com/introlab/find-object), being able to detect multiple occurences of the same object.
![alt text](https://raw.githubusercontent.com/wiki/introlab/find-object/doc/tutorial4/1.png "Detection of multiple occurrences of the same object")

# Many objects detection
Another example, still based on find-object](https://github.com/introlab/find-object), to detect many objects in a scene.
![alt text](https://raw.githubusercontent.com/wiki/introlab/find-object/doc/tutorial5/results1000.jpg "Detection of multiple occurrences of the same object")

Thanks in advance for your insights and inputs on these topics.

Cheers,
X

**Comment by yzhangcs** [comment]
Hi, this repo may not be able to do the above points.
The code only implements the feature extraction and matching of the whole image (w/o involving image segmentation, etc.).

**Comment by x0rzkov** [comment]
Is it something you can consider to add ? It would make of SoTu a modern CBIR. ^^

**Comment by yzhangcs** [comment]
Thanks for your advice.
But this project is a sort of toy system as my graduation project. At present, my main research topic is NLP, so I don't have enough free time to add more features:joy:. 
If you are willing to go further, I refer you to read this [book](https://github.com/jesolem/PCV), which I benefit a lot from when building SoTu.
